const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getProjects: () => ipcRenderer.invoke('get-projects'),
  getClaudeStatus: () => ipcRenderer.invoke('get-claude-status'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  getStats: () => ipcRenderer.invoke('get-stats'),
  getVscodeOpen: () => ipcRenderer.invoke('get-vscode-open'),
  getPrStatus: () => ipcRenderer.invoke('get-pr-status'),
  getDisplays: () => ipcRenderer.invoke('get-displays'),
  setPeek: (opts) => ipcRenderer.send('set-peek', opts),
  setSetting: (kv) => ipcRenderer.invoke('set-setting', kv),
  toggleFavorite: (p) => ipcRenderer.invoke('toggle-favorite', p),
  createProject: (data) => ipcRenderer.invoke('create-project', data),
  cloneRepo: (data) => ipcRenderer.invoke('clone-repo', data),
  openProject: (p) => ipcRenderer.send('open-project', p),
  ackSession: (id) => ipcRenderer.send('ack-session', id),
  setMode: (expanded) => ipcRenderer.send('set-mode', expanded),
  itemMenu: (p) => ipcRenderer.send('item-menu', p),
  dragStart: () => ipcRenderer.send('drag-start'),
  dragEnd: () => ipcRenderer.send('drag-end'),
  resetPos: () => ipcRenderer.send('reset-pos'),
  onMode: (cb) => ipcRenderer.on('mode', (_e, v) => cb(v)),
  onRefresh: (cb) => ipcRenderer.on('refresh', () => cb()),
  onClaudeStatus: (cb) => ipcRenderer.on('claude-status', (_e, v) => cb(v)),
  onGitStatus: (cb) => ipcRenderer.on('git-status', (_e, v) => cb(v)),
  onConfig: (cb) => ipcRenderer.on('config', (_e, v) => cb(v)),
  onToast: (cb) => ipcRenderer.on('toast', (_e, v) => cb(v)),
  onVscodeOpen: (cb) => ipcRenderer.on('vscode-open', (_e, v) => cb(v)),
  onPrStatus: (cb) => ipcRenderer.on('pr-status', (_e, v) => cb(v)),
  onStats: (cb) => ipcRenderer.on('stats', (_e, v) => cb(v)),
  onChime: (cb) => ipcRenderer.on('chime', (_e, v) => cb(v)),
  onPeek: (cb) => ipcRenderer.on('peek', (_e, v) => cb(v)),
  onDock: (cb) => ipcRenderer.on('dock', (_e, v) => cb(v)),
});
